import { TreePine, Droplets, Zap, Recycle, Globe, Users } from "lucide-react";

const ImpactStats = () => {
  const stats = [
    {
      icon: TreePine,
      value: "2.5M",
      label: "Trees Planted",
      description: "Through our reforestation projects",
      color: "text-primary"
    },
    {
      icon: Droplets,
      value: "1.8B",
      label: "Liters Water Saved",
      description: "Via conservation techniques learned",
      color: "text-accent"
    },
    {
      icon: Zap,
      value: "500K",
      label: "kWh Clean Energy",
      description: "Generated by student projects",
      color: "text-nature"
    },
    {
      icon: Recycle,
      value: "15M",
      label: "kg Waste Recycled",
      description: "Through community initiatives",
      color: "text-secondary"
    },
    {
      icon: Globe,
      value: "450",
      label: "Communities Impacted",
      description: "Worldwide environmental projects",
      color: "text-primary"
    },
    {
      icon: Users,
      value: "100K",
      label: "Eco-Champions",
      description: "Trained environmental leaders",
      color: "text-accent"
    }
  ];

  return (
    <section className="py-20 relative overflow-hidden">
      {/* Background Pattern */}
      <div className="absolute inset-0 opacity-5">
        <div className="absolute top-10 left-10 w-32 h-32 gradient-forest rounded-full" />
        <div className="absolute bottom-20 right-20 w-40 h-40 bg-nature rounded-full" />
        <div className="absolute top-1/2 left-1/4 w-24 h-24 bg-accent rounded-full" />
      </div>

      <div className="container mx-auto px-4 relative">
        {/* Section Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center space-x-2 eco-badge mb-4">
            <Globe className="w-4 h-4" />
            <span>Real-World Impact</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold text-foreground mb-6">
            Creating Measurable
            <span className="gradient-nature bg-clip-text text-transparent"> Change</span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
            Our students don't just learn about environmental issues—they solve them. 
            See the tangible impact of our global community of eco-champions.
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {stats.map((stat, index) => (
            <div 
              key={index}
              className="learning-card text-center group hover-glow"
            >
              <div className={`w-16 h-16 mx-auto mb-6 rounded-2xl bg-gradient-subtle flex items-center justify-center ${stat.color} group-hover:scale-110 transition-spring`}>
                <stat.icon className="w-8 h-8" />
              </div>
              
              <div className="space-y-2">
                <div className={`text-4xl font-bold ${stat.color}`}>
                  {stat.value}
                </div>
                <h3 className="text-xl font-semibold text-foreground">
                  {stat.label}
                </h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {stat.description}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="text-center mt-16">
          <div className="inline-flex items-center space-x-4 bg-card rounded-2xl p-8 shadow-card hover:shadow-eco transition-smooth">
            <div className="flex -space-x-2">
              <div className="w-12 h-12 rounded-full gradient-forest flex items-center justify-center text-primary-foreground font-bold">
                🌱
              </div>
              <div className="w-12 h-12 rounded-full bg-nature flex items-center justify-center text-nature-foreground font-bold">
                🌍
              </div>
              <div className="w-12 h-12 rounded-full bg-accent flex items-center justify-center text-accent-foreground font-bold">
                💚
              </div>
            </div>
            <div className="text-left">
              <div className="text-lg font-semibold text-foreground">
                Join the Movement
              </div>
              <div className="text-muted-foreground">
                Be part of the next generation of environmental leaders
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ImpactStats;