// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kifdcifcfoozlndneoej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZmRjaWZjZm9vemxuZG5lb2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDQ0NTEsImV4cCI6MjA3NDAyMDQ1MX0.2BLPlqbGbdSh1eAUrO1A46N8amr0FHcV_X_urJV05zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});